### ISSUE TITLE
freshness defficiency

### ISSUE THREAD

**Issue by AlonzoTG** [abusse/xeon-phi-overlay#1]
Hey, as of a few weeks ago, the latest version is 3.4.1. Is there going to be any commitment to keeping the versions fresh? =\ If not, it would be more helpful to have a detailed walkthrough for manually building the suite. I can't find a layman command to add it anyway. =(

**Comment by abusse** [comment]
Hey, the repository was mainly meant for my personal convenience. I never thought that someone else wanted to use it. Thats also why there is no convenient way to use it with layman. It is just a clone of the local overlay of the Phi Host.

Nevertheless I was planing to upgrade the ebuilds to the new MPSS over the christmas holidays. But let be said that those ebuild were only tested on one single machine, so I am pretty sure they will not work completely out of the box. I already found some problems with the current ones (that I will fix of course) but I am sure there will be more!

**Comment by abusse** [comment]
I just updated everything to 3.4.2. So let me know if there are issues, since I have only one machine for testing.
